version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"              # avoid 3.13 surprises for now
  jobs:
    post_install:
      - python -c "import myst_parser, sys; print('MyST OK', myst_parser.__version__)"
      # optional quick sanity check

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
